### ISSUE TITLE
Unable to 'make'

### ISSUE THREAD

**Issue by ejans** [komar007/ukbdc#5]
Dear Michal ,

could you explain the dependencies to compile this source code.
I seem to have an issue with the defined templates into the Makefile and am unable to make any targets other than bin/.

Kind regards,

Evert

**Comment by komar007** [comment]
It might be a problem with the version of make or avr-gcc. Please provide the full error message.
Thanks.

**Comment by ejans** [comment]
Error message:

$ make
make: **\* No rule to make target `gh60', needed by`all'.  Stop.

It seems like the targets defined in Makefile.config are not picked up?

Versions:

$ avr-gcc -v
Using built-in specs.
COLLECT_GCC=avr-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/avr/4.8.2/lto-wrapper
Target: avr
Configured with: ../src/configure -v --enable-languages=c,c++ --prefix=/usr/lib --infodir=/usr/share/info --mandir=/usr/share/man --bindir=/usr/bin --libexecdir=/usr/lib --libdir=/usr/lib --enable-shared --with-system-zlib --enable-long-long --enable-nls --without-included-gettext --disable-libssp --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=avr
Thread model: single
gcc version 4.8.2 (GCC)

$ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu

Should I try the latest version of make?

Kind regards,

Evert

**Comment by ejans** [comment]
Just tested this with make 4.0 and it works.

Thanks!

Evert

**Comment by komar007** [comment]
As far as I remember it required >=make-3.82.
I'm glad it works now.
